version: '3.4'

services:
  bankmanagementsystemservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "mssql-server"
    ports:
      - "8000:80"

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "2Secure*Password2"
    ports:
      - "1433:1433"
    
